/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.rudyreyes.analizadorlexico.vista;

import com.rudyreyes.analizadorlexico.token.Token;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rudyo
 */
public class VentanaReportes extends javax.swing.JDialog {

    /**
     * Creates new form VentanaReportes
     */
    private List<Token> tokens;
    public VentanaReportes(java.awt.Frame parent, boolean modal,  List<Token> tokens) {
        super(parent, modal);
        this.tokens= tokens;
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) tablaReportes.getModel();
        for (Token token : tokens) {
            model.addRow(new Object[]{
                colorearToken(token.getTipo(), token.getTipo()),
                colorearToken(token.getTipo(), token.getPatron()),
                colorearToken(token.getTipo(), token.getValor()),
                colorearToken(token.getTipo(), token.getLinea()+""),
                colorearToken(token.getTipo(), token.getColumna()+"")
            });
        }
    }
    
    private String colorearToken(String tipo, String palabra){
        if(tipo.equals("Identificador")){
            return "<html><font color='black'>"+palabra+"</font></html>";
        
        }else if (tipo.equals("OperadorAsignacion") || tipo.equals("OperadorLogico") 
                || tipo.equals("OperadorComparacion") ||  tipo.equals("OperadorAritmetico") ){
            return "<html><font color='#00BFFF'>"+palabra+"</font></html>";
        
        
        }else if(tipo.equals("PalabraClave")){
            return "<html><font color='#800080'>"+palabra+"</font></html>";
        
        }else if(tipo.equals("Constante")){
            return "<html><font color='red'>"+palabra+"</font></html>";
        
        }else if(tipo.equals("Comentario")){
            return "<html><font color='#C0C0C0'>"+palabra+"</font></html>";
        
        }else {
            return "<html><font color='green'>"+palabra+"</font></html>";
        }
        
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();
        etiquetaTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token", "Patron", "Lexema", "Linea", "Columna"
            }
        ));
        jScrollPane1.setViewportView(tablaReportes);

        etiquetaTitulo.setText("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(etiquetaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReportes;
    // End of variables declaration//GEN-END:variables
}
